version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./temp:/app/temp
    environment:
      - NODE_ENV=production
      - PORT=3000